FROM alpine:3.1

# Update
RUN apk add --update python py-pip

# Install app dependencies
RUN pip install Flask

# Bundle app source
COPY ~/pyproject/helloworld/test.py test.py
COPY ~/pyproject/helloworld/requirements.txt requirements.txt

EXPOSE  8000
CMD ["python", "~/pyproject/helloworld/test.py", "-p 8000"]
